login:
    viewModel: 'Tasks/Login'
    templateId: 'login-template'
register:
    viewModel: 'Tasks/Register'
    templateId: 'register-template'
home:
    viewModel: 'Tasks/Home'
    templateId: 'home-template'
logout:
    viewModel: 'Tasks/Logout'
    templateId: 'logout-template'
gameOverview:
    viewModel: 'Tasks/Game/GameOverview'
    templateId: 'game-overview-template'
addGameDialog:
    viewModel: 'Dialogs/Game/AddGame'
    templateId: 'dialog-add-game-template'
removeGameDialog:
    viewModel: 'Dialogs/Game/RemoveGame'
    templateId: 'dialog-remove-game-template'