CoreBundle\Entity\Code:
    type: entity
    table: codes
    repositoryClass: CoreBundle\Repository\Code
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        gameId:
            type: integer
            nullable: false
            name: game_id
            options:
                unsigned: false
        code:
            type: string
            nullable: false
            length: 255
            name: code
            options:
                fixed: false
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: code
    lifecycleCallbacks: {  }