CoreBundle\Entity\User:
    type: entity
    table: users
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        name_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        timestamp:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }