<?php

namespace CoreBundle\Repository;

/**
 * Code
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Code extends \Doctrine\ORM\EntityRepository {
    /**
     * Gets all game names and the amount of save codes for the games by an user id.
     * @param Integer $gameId
     * @return Array
     */
    public function getAllCodesByGame($gameId) {
        $stmt = 'SELECT c.id, c.description, c.code
                   FROM codes c
                  WHERE c.game_id = :gameId';
        $params = [
            'gameId' => $gameId
        ];
        return $this->_em->getConnection()->executeQuery($stmt, $params)->fetchAll(\PDO::FETCH_ASSOC);
    }
}
