<?php

namespace CoreBundle\Repository;

/**
 * Game
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Game extends \Doctrine\ORM\EntityRepository {
    
    /**
     * Gets all game names and the amount of save codes for the games by an user id.
     * @param Integer $userId
     * @return Array
     */
    public function getAllGamesByUserId($userId) {
        $stmt = 'SELECT g.id, g.name, g.amount_of_save_codes 
                   FROM games g
                  WHERE g.user_id = :userId';
        $params = [
            'userId' => $userId
        ];
        return $this->_em->getConnection()->executeQuery($stmt, $params)->fetchAll(\PDO::FETCH_ASSOC);
    }
}
